name: Deploy website on push
on:
  push:
    branches:
      - main # Asegúrate de que esta es la rama correcta

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3 # Actualizado a v3

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftpupload.net	
          username: if0_35291493
          password: ${{ secrets.FTP_PASSWORD }}
